# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  check:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOFLAG: -mod=readonly
      - image: vault:1.1.0
        environment:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf

    resource_class: small

    steps:
      - checkout

      - restore_cache:
          name: Restore Go module cache
          keys:
          - gomod-v3-{{ checksum "go.sum" }}
          - gomod-v3

      - run:
          name: Install dependencies
          command: go mod download

      - save_cache:
          name: Save Go module cache
          key: gomod-v3-{{ checksum "go.sum" }}
          paths:
              - /go/pkg/mod

      - restore_cache:
          name: Restore license cache
          keys:
              - licensei-v3-{{ checksum "go.sum" }}
              - licensei-v3

      - run:
          name: Download license information for dependencies
          command: make license-cache

      - save_cache:
          name: Save license cache
          key: licensei-v3-{{ checksum "go.sum" }}
          paths:
              - .licensei.cache

      - run:
          name: Check dependency licenses
          command: make license-check

      - run:
          name: Run verification
          environment:
            VAULT_ADDR: http://localhost:8200
            VAULT_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf
          command: make check

  acceptance-test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOFLAG: -mod=readonly

    environment:
      GO_VERSION: "1.12.6"
      K8S_VERSION: v1.14.0
      VAULT_VERSION: "1.1.0"
      KUBECONFIG: /home/circleci/.kube/kind-config-kind
      KIND_VERSION: v0.3.0
      DOCKER_LATEST: 1
      GIN_MODE: release

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Setup kind
          command: |
            curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/

      - run:
          name: Start kind cluster
          background: true
          command: |
            kind create cluster

      - run:
          name: Setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube

      - checkout

      - restore_cache:
          name: Restore Go module cache
          keys:
          - gomod-v3-{{ checksum "go.sum" }}
          - gomod-v3

      - run:
          name: Build Docker images
          command: |
            make docker
            make docker-operator
            make docker-vault-env
            make docker-webhook

      - run:
          name: Wait for kind cluster
          command: |
            timeout 180s bash <<EOT
              set -o pipefail

              function is_ready()
              {
                kubectl get nodes -o json \
                  | jq '.items[].status.conditions[] | select(.type=="Ready" and .status=="True")'
              }

              until is_ready
              do
                sleep 1
              done
            EOT

      - run:
          name: Load images to kind
          command: |
            kind load docker-image banzaicloud/bank-vaults:latest
            kind load docker-image banzaicloud/vault-operator:latest
            kind load docker-image banzaicloud/vault-secrets-webhook:latest
            kind load docker-image banzaicloud/vault-env:latest

      - run:
          name: Setup helm
          command: |
            curl -L https://git.io/get_helm.sh | bash
            helm init
            helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com/

      - run:
          name: Operator and webhook acceptance test
          command:
            hack/acceptance-test.sh

workflows:
  version: 2
  ci:
    jobs:
      - check
      - acceptance-test:
          requires:
            - check
